// 
// Generated by ChatGPT, OpenAI, April 4, 2025
// This file is part of the Week5.Models namespace and defines the ClassInformationTable class.

namespace Week5.Models
{
    public class ClassInformationTable
    {
        public string ClassName { get; set; }
        public int StudentCount { get; set; }
        public string Description { get; set; }

        // ID will only be used for operations (edit/delete)
        public int Id { get; set; }
    }
}
