/*

this part generated by ChatGPT, OpenAI, April 4, 2025
Prompt used: "Create a C# model class for class information table display with:
- Id property (not displayed in UI but used for backend operations)
- ClassName as string
- StudentCount as integer
- Description as string
- Default string initialization"

*/

using System.ComponentModel.DataAnnotations;

namespace Week5.Models
{
    public class ClassInformationTable
    {
  
        public int Id { get; set; }

        public string ClassName { get; set; } = string.Empty;

        public int StudentCount { get; set; }

        public string Description { get; set; } = string.Empty;
    }
}
